name: Daily commit

on:
  schedule:
    - cron: '15 12 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Make commit
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git commit --allow-empty -m "Daily commit $(date +'%Y-%m-%d')"
        git push origin HEAD:main
