name: Automatic commit

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Make commit
      run: |
        git config user.name "Rocky04"
        git config user.email "olegtsynkovskiy@gmail.com"
        git add .
        git commit -m "Automatic commit $(date +%Y-%m-%d)"
        git push
